version: '2'
services:
    aresvi-app:
        image: caballerojavier13/admin_aresvi:3.2.0
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://aresvi-mysql:3306/aresvi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    aresvi-mysql:
        extends:
            file: mysql.yml
            service: aresvi-mysql
