version: '2'
services:
    aresvi-mysql:
        image: mysql:5.7.19
        # volumes:
        #     - ~/volumes/jhipster/AresVI/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=no
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=aresvi
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
